[project]
name = "parahod"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.22.0",
    "fastapi>=0.117.1",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.37.0",
]
